### ISSUE TITLE
Add jxmapviewer2

### ISSUE THREAD

**Issue by homebeaver** [homebeaver/SwingSet#43]
... damit man auch Karten darstellen kann

**Comment by homebeaver** [comment]
etwa so:

![grafik](https://user-images.githubusercontent.com/3493126/211937334-6bd2eecf-b240-474a-92c5-6a3f0df0e3d7.png)

**Comment by homebeaver** [comment]
am besten
- als maven subproject und artifact **swingx-mapviewer**
- und separetem jar `swingx-mapviewer-1.7.5.jar`

**Comment by ChristianCiach** [comment]
Es ist schade, dass diese Library nun mit den Packages von https://github.com/msteiger/jxmapviewer2/ konfliktiert, denn diese Library ist aktuell in Version 2.8 (welche wir benötigen), während in SpringSet3 quasi Version 2.6 enthalten ist. Ich hätte es schöner gefunden, wenn hier ein anderer Package-Name verwendet worden wäre, um Konflikte zu vermeiden.

Edit: Pragmatischer Workaround: Transitive Dependency  `io.github.homebeaver:swingx-mapviewer` excluden und `org.jxmapviewer:jxmapviewer2:2.8` direkt einbinden.
