### ISSUE TITLE
More changes to SwingX

### ISSUE THREAD

**Issue by wlfbck** [homebeaver/SwingSet#61]
In the SwingSet3 project issues are disabled, so i have no other way of contacting you.

While looking for more current versions of swingx (in general), i also found https://mvnrepository.com/artifact/at.swimmesberger/swingx-all

Unfortunately no official repo is linked to it, but swimmesberger is on github. There is a source jar attached on maven as well. Not sure what he changed compared to you, but it might be interesting to find out and maybe integrate some of it.

**Comment by homebeaver** [comment]
Thx @wlfbck ,

My newest Release is

```
<!-- https://mvnrepository.com/artifact/io.github.homebeaver/swingset3 -->
<dependency>
    <groupId>io.github.homebeaver</groupId>
    <artifactId>swingset3</artifactId>
    <version>1.7.6</version>
    <type>pom</type>
</dependency>
```

dated Aug 24, 2023

regards EUGen H.

**Comment by homebeaver** [comment]
in at/swimmesberger/swingx-core/1.6.8 entspricht 

- https://github.com/homebeaver/SwingSet3/releases/tag/v1.6.8 bzw
- https://github.com/homebeaver/SwingSet3/releases/tag/v1.6.7
